### ISSUE TITLE
Ability to apply mapping function over env var

### ISSUE THREAD

**Issue by kubek2k** [voldern/get-env-var#2]
Idea is to be able to apply mapping function on retrieved values. My idea is to have something like this:

```
const intEnv = getEnvVar("SOME_INT_ENV").map(Number.parseInt).required();
```

and for optional values with default

```
const intEnv = getEnvVar("SOME_INT_ENV").map(Number.parseInt).orDefaultValue(42);
```

but that breaks backwards compability. The other way could be to introduce third argument, but then you can't stack applied functions, and it looks a bit of awkward (esp. when you want to have a mapping function over a value that is required).

**Comment by voldern** [comment]
What do you think about the following API?

``` javascript
/* String, [defaultValue], [mappingFunction] */

getEnvVar('SOME_INT_ENV', 10, Number.parseInt);
getEnvVar('SOME_INT_ENV', Number.parseInt);
getEnvVar('SOME_BOOL_ENV', true, value => value === 'true');
getEnvVar('SOME_BOOL_ENV', value => value === 'true');
```

If you need to apply more mappings you need to compose the functions using for example https://lodash.com/docs#flow

``` javascript
getEnvVar('SOME_INT_ENV', _.flow(Number.parseInt, value => value + 10));
```

**Comment by kubek2k** [comment]
Well looks valid, but what are the advantages over my proposal? Plus: still
awkward when it comes to required values, that you would like to convert.
PS: I like currying 😉

**Comment by voldern** [comment]
> Well looks valid, but what are the advantages over my proposal?

It's more idiomatic NodeJS. It's not very common to return an object from a function call in order to support chaining like in your proposed API.

> Plus: still awkward when it comes to required values, that you would like to convert.

I'm not sure I see the benefit of being able to map over the default value in a non-explicit way, since you have control over that input.

In my mind this approach gives the most flexibility. You could choose to apply a function only to the ENV value, only to the default value, both, or some combination:

``` javascript
getEnvVar('SOME_INT_VALUE', 15, Number.parseInt);
getEnvVar('SOME_STRING_VALUE', _.snakeCase('foo bar'));
_.clamp(getEnvVar('SOME_INT_VALUE', 15), 100);
_.clamp(getEnvVar('SOME_INT_VALUE', _.add(15, 10), Number.parseInt), 100);
```

Have I overlooked or misunderstood something?

**Comment by kubek2k** [comment]
> It's more idiomatic NodeJS. It's not very common to return an object from a function call in order to support chaining like in your proposed API.

I thought there is something behind it. Thanks for explanation :+1:

> getEnvVar('SOME_STRING_VALUE', _.snakeCase('foo bar'));

I guess it would be based on type checking of positional parameters. Looks legit anyways!

> Have I overlooked or misunderstood something?

No... thats just me coming with some wrong background ;)

**Comment by kubek2k** [comment]
:bow:
